theme: jekyll-theme-leap-day
title: Sankhya SDK (.NET)
description: ğŸ“Š âš™ï¸ Sankhya platform .NET SDK
logo: https://raw.githubusercontent.com/guibranco/Sankhya-SDK-dotnet/master/packageLogo.png
show_downloads: true
